system:
  name: FinanceRAG-Pro
  version: 1.0.0
  debug: false
  log_level: INFO

models:
  query_understanding:
    model: gpt-3.5-turbo
    fallback: Qwen2-7B-GPTQ
    temperature: 0.1
    max_tokens: 1000
  
  embedding:
    model: BAAI/bge-m3
    dimension: 1024
    batch_size: 32
    precision: fp16
  
  reranking:
    model: BAAI/bge-reranker-base
    top_k: 10
    precision: int8
  
  generation:
    model: Qwen/Qwen2.5-7B-Instruct-GPTQ
    precision: 4bit
    max_length: 2048
    temperature: 0.7

database:
  postgresql:
    host: localhost
    port: 5432
    database: financerag
    user: postgres
    password: password
  
  redis:
    host: localhost
    port: 6379
    db: 0
  
  chromadb:
    persist_directory: ./data/chromadb
    collection_name: finance_documents
  
  minio:
    endpoint: localhost:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: finance-docs
    secure: false

retrieval:
  chunk_size: 512
  chunk_overlap: 50
  top_k: 20
  similarity_threshold: 0.7
  enable_rerank: true

cache:
  enabled: true
  ttl: 3600
  max_size: 1000
  eviction_policy: LRU

performance:
  max_workers: 10
  batch_processing: true
  async_enabled: true
  timeout: 30

api:
  host: 0.0.0.0
  port: 8000
  cors_enabled: true
  docs_enabled: true
  max_request_size: 10485760