system:
  name: FinanceRAG-Pro
  version: 1.0.0
  debug: false
  log_level: INFO

# API密钥配置
api_keys:
  # 硅基流动 - 用于Qwen3-8B文本生成
  siliconflow: ${SILICONFLOW_API_KEY}  # 请在环境变量中设置
  
  # 魔搭 - 用于Qwen2.5-VL-72B视觉理解
  modelscope: ${MODELSCOPE_API_KEY}    # 请在环境变量中设置
  
  # OpenAI备用（如果需要）
  openai: ${OPENAI_API_KEY}

# 模型配置
models:
  # 查询理解模型（使用硅基流动Qwen3-8B）
  query_understanding:
    provider: siliconflow
    model: Qwen/Qwen3-8B
    temperature: 0.1
    max_tokens: 1000
    # 非批量模式限制
    rpm_limit: 1000
    tpm_limit: 5000
    min_request_interval: 0.06
    # 批量模式限制
    batch_rpm_limit: 100
    batch_tpm_limit: 50000
    batch_min_interval: 0.6
  
  # 生成模型（使用硅基流动Qwen3-8B）
  generation:
    provider: siliconflow
    model: Qwen/Qwen3-8B
    temperature: 0.7
    max_tokens: 2000
    rpm_limit: 1000
    tpm_limit: 5000
    min_request_interval: 0.06
    batch_rpm_limit: 100
    batch_tpm_limit: 50000
    batch_min_interval: 0.6
  
  # 视觉语言模型（使用魔搭Qwen2.5-VL-72B）
  vision_language:
    provider: modelscope
    model: qwen-vl-72b-instruct
    temperature: 0.1
    max_tokens: 2000
    # 非批量模式限制
    rpm_limit: 30
    tpm_limit: 3000
    min_request_interval: 2
    # 批量模式限制
    batch_rpm_limit: 10
    batch_tpm_limit: 10000
    batch_min_interval: 6
  
  # 嵌入模型（本地运行）
  embedding:
    model: BAAI/bge-m3
    dimension: 1024
    batch_size: 32
    precision: fp16
  
  # 重排序模型（本地运行）
  reranking:
    model: BAAI/bge-reranker-base
    top_k: 10
    precision: int8

# 批处理配置
batch_processing:
  enabled: true
  default_batch_size: 10
  max_retries: 3
  checkpoint_enabled: true
  checkpoint_dir: ./checkpoints

# 数据库配置
database:
  postgresql:
    host: localhost
    port: 5432
    database: financerag
    user: postgres
    password: postgres123
  
  redis:
    host: localhost
    port: 6379
    db: 0
  
  chromadb:
    persist_directory: ./data/chromadb
    collection_name: finance_documents
  
  minio:
    endpoint: localhost:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: finance-docs
    secure: false

# 检索配置
retrieval:
  chunk_size: 512
  chunk_overlap: 50
  top_k: 20
  similarity_threshold: 0.7
  enable_rerank: true

# 缓存配置
cache:
  enabled: true
  ttl: 3600
  max_size: 1000
  eviction_policy: LRU

# 性能配置
performance:
  max_workers: 10
  batch_processing: true
  async_enabled: true
  timeout: 30
  # 批量模式设置
  batch_mode: false  # 设置为true启用批量模式

# API服务配置
api:
  host: 0.0.0.0
  port: 8000
  cors_enabled: true
  docs_enabled: true
  max_request_size: 10485760

# 限流配置汇总
rate_limits:
  siliconflow:
    normal:
      rpm: 1000
      tpm: 5000
      min_interval: 0.06
    batch:
      rpm: 100
      tpm: 50000
      min_interval: 0.6
  modelscope:
    normal:
      rpm: 30
      tpm: 3000
      min_interval: 2
    batch:
      rpm: 10
      tpm: 10000
      min_interval: 6